translate mintable xc-20, permits and other xcm changes
PureStake/moonbeam-docs-cn pull request #119
Opened 2022-06-24 11:25 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/319
https://github.com/PureStake/moonbeam-docs/pull/329
https://github.com/PureStake/moonbeam-docs/pull/334

This does not include the XCM transactor PR. 

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-06-24 20:33 UTC, eshaben requested changes
this was a big PR... nice job! just some minor things!

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/overview.md
> +2. 编译**IER20.sol**文档
```suggestion
2. 编译**IERC20.sol**文档
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +如同[XC-20概况](/builders/xcm/xc20/overview){target=_blank}页面中所述，[XC-20有两种类型](/builders/xcm/xc20/overview#types-of-xc-20s)：外部的和[可铸造的](/builders/xcm/xc20/overview#types-of-xc-20s){target=_blank}。外部和可铸造的XC
```suggestion
如同[XC-20概况](/builders/xcm/xc20/overview){target=_blank}页面中所述，[XC-20有两种类型](/builders/xcm/xc20/overview#types-of-xc-20s){target=_blank}：外部的和[可铸造的](/builders/xcm/xc20/overview#types-of-xc-20s){target=_blank}。外部和可铸造的XC-20之间最大的不同为外部XC-20代表那些在中继链或是其他平行链中锁定在Moonbeam主权账户的资产。相反地，可铸造XC-20代表那些直接在Moonbeam链上铸造或是销毁的资产但拥有原生XCM互操作性功能。此教程将涵盖外部XC-20类型的资产。 
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +     _*You can check each [Asset ID](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbeam.network#/assets){target=_blank} on Polkadot.js Apps_
this can be translated

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +    _*You can check each [Asset ID](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonriver.moonbeam.network#/assets){target=_blank} on Polkadot.js Apps_
this too

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +     _*You can check each [Asset ID](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.api.moonbase.moonbeam.network#/assets){target=_blank} on Polkadot.js Apps_
and this

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +  --8<-- 'text/xc-20/list-of-assets.md'
```suggestion
--8<-- 'text/xc-20/list-of-assets.md'
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xc20.md
> +    --8<-- 'text/xc-20/retrieve-metadata.md'
```suggestion
--8<-- 'text/xc-20/retrieve-metadata.md'
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
> +    | Parameter |     Value      |
```suggestion
    | 参数 |     数值      |
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
> +    | Parameter | Value |
```suggestion
    | 参数 | 数值 |
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
> +    |   Parameter    |     Value      |
```suggestion
    |   参数    |     数值      |
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
> +    | Parameter |     Value      |
```suggestion
    | 参数 |     数值      |
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
> + - **transfer**(*address* currency_address, *uint256* amount, *Multilocation* *memory* destination, *uint64* weight) —— 用于表示[先前示例](/builders/xcm/xc20/xtokens/#xtokens-transfers-function)中提及的`transfer
```suggestion
 - **transfer**(*address* currency_address, *uint256* amount, *Multilocation* *memory* destination, *uint64* weight) —— 用于表示[先前示例](/builders/xcm/xc20/xtokens/#xtokens-transfer-function)中提及的`transfer`函数。然而，在使用币种ID之外，您需要为`currency_address`提供资产预编译地址：
```

2022-06-24 20:33 UTC, eshaben commented on builders/xcm/xc20/xtokens.md
>  |   Origin    | Destination | Parents Value |
just noticed this... i think these table headers can be translated

2022-06-27 07:31 UTC, hyd628 commented
Thanks @eshaben for the fixes and feedback, I've pushed a commit for the missing translations.

2022-06-27 14:39 UTC, eshaben commented on builders/xcm/xc20/mintable-xc20.md
> +|     **角色**      | **铸造** | **销毁** | **锁定** | **解冻** |
```suggestion
|       角色       |   铸造   |   销毁   |   锁定   |   解冻   |
```

2022-06-27 14:40 UTC, merged