Xtokens snippet and learning pages links
PureStake/moonbeam-docs-cn pull request #146
Opened 2022-08-25 14:48 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/382/files
https://github.com/PureStake/moonbeam-docs/pull/387

Some changes to Randomness page will be included when the Randomness pages get translated. 

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-08-25 21:40 UTC, eshaben requested changes
just one thing!

2022-08-25 21:40 UTC, eshaben commented on builders/pallets-precompiles/pallets/staking.md
> +DPOS共识允许Token持有者（委托人）以准确表示他们希望支持的候选人（收集人）以及对收集人的质押量。此项平行链质押pallet的设计使得委托人和候选人（收集人）之间强制共享链上的风险/奖励。
This looks like it is missing a link.

English version:
```
The DPoS system is powered by the [parachain staking](https://github.com/PureStake/moonbeam/tree/master/pallets/parachain-staking/src){target=_blank} pallet, allowing token holders (delegators) to express exactly which collator candidates they would like to support and with what quantity of stake. The design of the parachain staking pallet is such that it enforces shared risk/reward on chain between delegators and candidates.
```

2022-08-26 08:59 UTC, hyd628 commented
Thanks @eshaben , incorporated the feedback.

2022-08-26 15:55 UTC, eshaben approved these changes
Sweet thanks! LGTM ✨

2022-08-26 15:55 UTC, merged