Small PRs
PureStake/moonbeam-docs-cn pull request #159
Opened 2022-09-13 04:00 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/404
https://github.com/PureStake/moonbeam-docs/blame/master/.snippets/text/batch/batch-interface.md#L7-L12
https://github.com/PureStake/moonbeam-docs/pull/393
https://github.com/PureStake/moonbeam-docs/pull/413

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-09-14 14:04 UTC, eshaben requested changes
Thanks @hyd628! Just one thing that needs to be reviewed

2022-09-15 01:19 UTC, hyd628 commented
Thanks @eshaben , incorporated the feedback.

2022-09-15 19:27 UTC, eshaben approved these changes
LGTM ✨

2022-09-15 19:27 UTC, eshaben commented on builders/pallets-precompiles/precompiles/staking.md
> + - **scheduleLeaveDelegators**() —— 发起离开委托人集并撤回所有进行中的委托的请求。发起请求并不会自动执行，需要等待[退出延迟](#exit-delays)，您可以通过`executeLeaveDelegators`函数执行请求。使用质押Pallet的[`scheduleLeaveDelegators`](/builders/pallets-precompile
```suggestion
 - **scheduleLeaveDelegators**() —— 发起离开委托人集并撤回所有进行中的委托的请求。发起请求并不会自动执行，需要等待[退出延迟](#exit-delays)，您可以通过`executeLeaveDelegators`函数执行请求。可以使用[批量处理方法](/builders/pallets-precompiles/pallets/utility/#using-the-batch-extrinsics){target=_blank}来打包多个`scheduleLeaveDelegators`请求
```

2022-09-15 19:27 UTC, eshaben commented on builders/pallets-precompiles/precompiles/staking.md
> + - **executeLeaveDelegators**(*address* delegator, *uint256* delegatorDelegationCount) —— 执行离开委托人集和撤回所有委托的可用请求。使用质押Pallet的[`executeLeaveDelegators`](/builders/pallets-precompiles/pallets/staking/#:~:
```suggestion
 - **executeLeaveDelegators**(*address* delegator, *uint256* delegatorDelegationCount) —— 执行离开委托人集和撤回所有委托的可用请求。可以使用[批量处理方法](/builders/pallets-precompiles/pallets/utility/#using-the-batch-extrinsics){target=_blank}来打包多个`executeLeaveDelegators`请求
```

2022-09-15 19:27 UTC, eshaben commented on builders/pallets-precompiles/precompiles/staking.md
> + - **cancelLeaveDelegators**() —— 取消待处理的离开委托人集的请求。使用质押Pallet的[`cancelLeaveDelegators`](/builders/pallets-precompiles/pallets/staking/#:~:text=cancelLeaveDelegators()){target=_blank}函数。可以使用[批量处理方法](/b
```suggestion
 - **cancelLeaveDelegators**() —— 取消待处理的离开委托人集的请求。可以使用[批量处理方法](/builders/pallets-precompiles/pallets/utility/#using-the-batch-extrinsics){target=_blank}来打包多个`cancelLeaveDelegators`请求
```

2022-09-15 20:20 UTC, merged