Reorder tabs
PureStake/moonbeam-docs-cn pull request #30
Opened 2021-12-15 21:18 UTC by eshaben

reorder network tabs!

1. Moonbeam
2. Moonriver
3. Moonbase Alpha
4. Moonbeam Dev Node

this PR also fixes some broken image paths

2021-12-16 12:55 UTC, albertov19 requested changes
@hyd628 please look at the comments I made. All aside, good!

2021-12-16 12:55 UTC, albertov19 commented on builders/interact/hardhat.md
> +=== "Moonbeam Dev Node"
Why do we have this here, but on other instances we had `Moonbeam开发节点` @hyd628

2021-12-16 12:55 UTC, albertov19 commented on builders/interact/truffle.md
> +=== "Moonbeam Dev Node"
Here as well  @hyd628

2021-12-16 12:55 UTC, albertov19 commented on node-operators/networks/tracing-node.md
> +=== "Moonbeam Dev Node"
Another one @hyd628

2021-12-16 12:55 UTC, albertov19 commented on tokens/connect/metamask.md
> +=== "Moonbeam Dev Node"
Another one @hyd628

2021-12-16 12:55 UTC, albertov19 commented on tokens/connect/nifty.md
> +=== "Moonbeam Dev Node"
Another one @hyd628

2021-12-16 13:58 UTC, hyd628 commented on builders/interact/hardhat.md
> +=== "Moonbeam Dev Node"
they are inconsistent. prob different people translated them. Moonbeam开发节点 is prob the better one to use here.

2021-12-16 14:54 UTC, albertov19 commented
@eshaben we need to change `Moonbeam Dev Node` for `Moonbeam开发节点` - besides that, all good

2021-12-21 14:26 UTC, albertov19 approved these changes

2021-12-21 14:29 UTC, merged