Port staking changes
PureStake/moonbeam-docs-cn pull request #34
Opened 2021-12-30 14:06 UTC by hyd628

### Description

Port staking changes to Chinese docs site.

### Checklist

- [x] If this requires translations for the `moonbeam-docs-cn` repo, I have created a ticket for the translations in Jira
- [x] If pages have been moved around, I have created an additional PR in `moonbeam-mkdocs` to update redirects
- [x] If images have been added, I have run the `compress-images.py` script to compress the images.
- [x] If images have been moved, I have created an additional PR in `moonbeam-docs-cn` to update images to their new paths
- [x] If variables (in variables.yml) need to be updated (such as a name change), I have updated the `moonbeam-docs-cn` repo to use the new variables

### Corresponding PRs

https://github.com/PureStake/moonbeam-docs/pull/215
https://github.com/PureStake/moonbeam-docs/pull/217
https://github.com/PureStake/moonbeam-docs/pull/219

### After Translation Requirements

- [ ] Will need to create PR in `moonbeam-docs` repo to remove images
- [ ] Will need to create PR in `moonbeam-docs` repo to remove variables
- [ ] Will need to create PR in `moonbeam-mkdocs` repo to add redirects for Chinese site
- [x] No additional PRs are required after the translations are done

#### Items to be Updated

None

2021-12-30 22:01 UTC, eshaben requested changes
Just a couple minor fixes are needed! Other than that it looks good ✨

2021-12-30 22:01 UTC, eshaben commented on node-operators/networks/collator.md
> +    | 最小自质押量 |     {{ networks.moonriver.staking.min_can_stk }} MOVR     |
looks like these use the same variables, only one is needed for Minimum self-bond amount

2021-12-30 22:01 UTC, eshaben commented on node-operators/networks/collator.md
> +    | 最小自质押量 |     {{ networks.moonbase.staking.min_can_stk }} DEV    |
same comment as above

2021-12-31 04:27 UTC, hyd628 commented
Good catch, thanks! The redundant entry is removed.

2021-12-31 15:40 UTC, eshaben approved these changes
sweeet LGTM! 🚀

2021-12-31 15:41 UTC, merged