Moonbeam related wallet changes
PureStake/moonbeam-docs-cn pull request #43
Opened 2022-01-17 16:41 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/224
https://github.com/PureStake/moonbeam-docs/pull/213/files
https://github.com/PureStake/moonbeam-docs/pull/231

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [ ] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [ ] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

2022-01-18 17:20 UTC, eshaben requested changes

2022-01-18 22:55 UTC, eshaben commented on builders/get-started/moonbeam.md
>  <!---
ah saw you made this change in another PR so nevermind this comment 👍

2022-01-19 03:14 UTC, hyd628 commented
Thanks @eshaben all feedbacks have been incorporated in the above commit.

2022-01-19 16:48 UTC, eshaben approved these changes
Awesome! LGTM ✨

2022-01-19 19:36 UTC, albertov19 approved these changes
LGTM

2022-01-19 19:36 UTC, merged