Port Moonbeam launch related changes
PureStake/moonbeam-docs-cn pull request #44
Opened 2022-01-18 09:39 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/223
https://github.com/PureStake/moonbeam-docs/pull/230
https://github.com/PureStake/moonbeam-docs/commit/bba3ec16670ade4943f41e0a154dfd2bbbc7491e

### Checklist

- [ ] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [ ] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [ ] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-01-19 00:19 UTC, eshaben requested changes
Ahh so many changes haha sorry to put this all in one PR! 😅 

It looks like there were some pages that were missed... 
-`builders/integrations/indexers/thegraph.md` (https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR18-R156)
- builders/tools/eth-dev-env/hardhat.md (https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-dc04a14539436f48bfe27667c2ed9e60ab0f2d8d369c78a4228f5a6fd6002b17R34-R73)
- learn/platform/tokens.md (https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-fdaa7573114446474b9a2a0616c6e7488e0abbc4b1090fd7a21516e0814a2e9cR17-R27) 👈 these seem to be minor just not sure if it makes a difference 🤷‍♀️ 
- node-operators/indexer-nodes/thegraph-node.md (https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-f31bdb0b960f43552a5a75f03c917375ee30034037933814d7d9664c7fee06dbR26-R127) 👈  Is this whole page out of date? It seemed to be... if there is a lot to translate we can open a different ticket for this. whatever you think is best!

2022-01-19 00:19 UTC, eshaben commented on learn/features/governance.md
> +    |         变量         |  |                                                            Value                                                             |
should value be translated?

2022-01-19 00:19 UTC, eshaben commented on learn/features/treasury.md
> +    |            变量             |  |                                                        Value                                                         |
same comment here as above - should value be translated?

2022-01-19 00:19 UTC, eshaben commented on learn/features/governance.md
> +    |         变量         |  |                                                            Value                                                             |
same goes for the Moonriver and Moonbase Alpha

2022-01-19 00:19 UTC, eshaben commented on tokens/governance/proposals.md
> +    |         变量         |  |                                                          Value                                                          |
same comment here as before... should value be translated?

2022-01-19 00:19 UTC, eshaben commented on tokens/governance/voting.md
> +    |       变量         |  |                                                         Value                                                         |
same comment here about value

2022-01-19 00:22 UTC, eshaben requested changes

2022-01-19 00:22 UTC, eshaben commented on builders/tools/eth-libraries/web3js.md
> +=== "Moonbeam Dev Node"
This should be Moonbeam开发节点 I think

2022-01-19 00:22 UTC, eshaben commented on builders/tools/eth-libraries/web3py.md
> +=== "Moonbeam Dev Node"
This should be Moonbeam开发节点 I think

2022-01-19 00:22 UTC, eshaben commented on builders/tools/sidecar.md
>  === "Moonbeam Dev Node"
This should be Moonbeam开发节点 I think

2022-01-19 00:24 UTC, eshaben commented on learn/features/governance.md
> +    |         变量         |  |                                                            Value                                                             |
I would maybe do a search in the repo for all use cases of "Variable" and Value" and update those cause I actually just noticed that "Variable" isn't translated here https://github.com/PureStake/moonbeam-docs-cn/pull/44/files#diff-c9c61564fa95109849566c20d6079bb70faa093f2ccb926fad1ad3a43ef123c9R39-R45

2022-01-19 03:13 UTC, hyd628 commented
Thanks for the feedback @eshaben . 

builders/integrations/indexers/thegraph.md was updated in a separate PR and merged: https://github.com/PureStake/moonbeam-docs-cn/commit/9dade795f1edd6f4a92d228cf4301dcc36190823

builders/tools/eth-dev-env/hardhat.md: missed this because there was another hardhat file, should be updated now.

learn/platform/tokens.md: the tense changes dont need to be translated (tenses are usually not explicit in Chinese), but I did find another unrelated issue, which I edited. 

node-operators/indexer-nodes/thegraph-node.md : updated this file. missed it because i just skipped anything related to the graph due to the other PR opened. 

Thanks!

2022-01-19 16:46 UTC, eshaben requested changes

2022-01-19 16:46 UTC, eshaben commented on node-operators/indexer-nodes/thegraph-node.md
> +=== "Moonbeam Dev Node"
this should be "Moonbeam开发节点"

2022-01-19 16:47 UTC, eshaben commented
@hyd628 

So it looks like not all of the updates were made on `builders/integrations/indexers/thegraph.md` - I know you updated it because it was out of date, but then it was updated again for the launch of Moonbeam and it seems like there were places where Moonbeam was added in but also a few places its missing:

- Moonbeam is not listed in the quick start section: [English changes](https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR22-R28) and [Chinese changes missing](https://github.com/PureStake/moonbeam-docs-cn/commit/9dade795f1edd6f4a92d228cf4301dcc36190823#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR24-R40)
- Checking Prerequisites section is missing the "can be adapted for Moonbeam or Moonriver" piece: [English changes](https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR52) and [Chinese changes missing](https://github.com/PureStake/moonbeam-docs-cn/commit/9dade795f1edd6f4a92d228cf4301dcc36190823#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR46)
- Subgraph Manifest section is missing part about Moonbeam and Moonriver: [English changes](https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR153) and [Chinese changes missing](https://github.com/PureStake/moonbeam-docs-cn/commit/9dade795f1edd6f4a92d228cf4301dcc36190823#diff-fd7e81c6b9974ef19edecab585c2900c991b8b59b331954e5de5d812e55911feR147)


I also happened to notice that I missed this page... it looks like `builders/tools/debug-trace.md` hasn't been updated: [English changes](https://github.com/PureStake/moonbeam-docs/pull/223/files#diff-274667756a18a6d0f20bb7a8f2aecce0f433538428ddcbddc45eb121f3d9e298R68-R115)

2022-01-20 07:55 UTC, hyd628 commented
@eshaben incorporated all the feedback. Thanks!

2022-01-24 19:16 UTC, eshaben approved these changes
LGTM ✨

2022-01-24 19:38 UTC, merged