Port staking changes
PureStake/moonbeam-docs-cn pull request #46
Opened 2022-01-19 08:53 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/222

### Checklist

- [ ] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [ ] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [ ] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-01-19 17:39 UTC, eshaben requested changes

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +
I think this space here is making it so the note doesn't appear correctly

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +## 账户与质押要求 {: #and-staking-requirements }
this should be `## Accounts and Staking Requirements {: #accounts-and-staking-requirements }`

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
>  ![Author ID Mapping Chain State](/images/node-operators/networks/collators/collator-polkadotjs-6.png)
After this there should be a section on Join the Discord: https://github.com/PureStake/moonbeam-docs/pull/229/files#diff-4a1e759dec4fe268e80b04913929273d86c98ee78cb33411197d028e1b3fb5b0R345-R355

2022-01-19 17:39 UTC, eshaben commented on learn/features/staking.md
> +If you're looking for candidate or collator-specific requirements and information, you can take a look at the [Collators](/node-operators/networks/collator) guide.
This needs to be translated still

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +### 发起离开候选人的请求
this is missing a header attribute now, it should still be `{: #schedule-request-to-leave-candidates }`

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +### 执行离开候选人的请求
this is missing header attribute, should be `{: #execute-request-to-leave-candidates }` still

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +### 取消离开候选人的请求
this should have this attribute still `{: #cancel-request-to-leave-candidates }`

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +#### 发起减少绑定数量的请求
should be `{: #schedule-bond-less-request }`

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +#### 执行减少绑定数量的请求
`{: #execute-bond-less-request }`

2022-01-19 17:39 UTC, eshaben commented on node-operators/networks/collator.md
> +#### 取消减少绑定数量的请求
`{: #cancel-bond-less-request }`

2022-01-19 17:39 UTC, eshaben commented on snippets/text/staking/staking-definitions.md
> + - **最高委托量（Maximu delegations）**—— 委托人能够委托的最高候选收集人数量
missing an m at the end of Maximum

2022-01-20 08:27 UTC, hyd628 commented
@eshaben Thanks! all feedback has been incorporated.

2022-01-21 15:24 UTC, eshaben approved these changes
Awesome! LGTM ✨🚀

2022-01-21 15:25 UTC, merged