Port collection of minor changes
PureStake/moonbeam-docs-cn pull request #55
Opened 2022-02-14 14:54 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/245/files
https://github.com/PureStake/moonbeam-docs/pull/241/files
https://github.com/PureStake/moonbeam-docs/compare/396c9a9abf3f793308ecbf4b5d201d643681b0e8...353558519f71d14be9d1ff242998228bdef054e6

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-02-14 21:37 UTC, eshaben requested changes

2022-02-14 21:37 UTC, eshaben commented on builders/integrations/indexers/thegraph.md
>    // "round_number" + "-" + "player_address" + "-" + "ticket_index_per_round"
this line can be deleted

2022-02-14 21:37 UTC, eshaben commented on builders/integrations/indexers/thegraph.md
>    let ticketId = roundId + "-" + playerId + "-" + nextTicketIndex;
this line can also be deleted

2022-02-14 21:37 UTC, eshaben commented on builders/tools/eth-dev-env/openzeppelin/defender.md
>  ![OpenZeppelin Defender Admin Contract New Pause Proposal](/images/builders/tools/eth-dev-env/openzeppelin/oz-defender-4.png)
this was as close as I could get to the actual link haha but line 125 should be updated to **Create pause proposal**

2022-02-14 21:37 UTC, eshaben commented on builders/tools/multisig-safe.md
the line below this one is missing {target=blank}

2022-02-14 21:38 UTC, eshaben commented on builders/integrations/indexers/thegraph.md
>    // "round_number" + "-" + "player_address" + "-" + "ticket_index_per_round"
this is displaying weird, but this line is the one that can be deleted `  // "round_number" + "-" + "player_address" + "-" + "ticket_index_per_round"`

2022-02-14 21:38 UTC, eshaben commented on builders/integrations/indexers/thegraph.md
>    let ticketId = roundId + "-" + playerId + "-" + nextTicketIndex;
this line `  let ticketId = roundId + "-" + playerId + "-" + nextTicketIndex;`

2022-02-16 05:15 UTC, hyd628 commented
Thanks, feedback incorporated.

2022-02-16 17:24 UTC, eshaben approved these changes
LGTM

2022-02-16 17:26 UTC, merged