Snippets related change
PureStake/moonbeam-docs-cn pull request #59
Opened 2022-02-28 13:49 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/264/

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

https://github.com/PureStake/moonbeam-docs/pull/264/

2022-02-28 19:19 UTC, eshaben requested changes
just a couple of small things

2022-02-28 19:19 UTC, eshaben commented on builders/interact/eth-libraries/deploy-contract.md
> +In the first part of the script, the `web3` instance (or provider) is created using the 在此脚本的第一部分，`web3`实例（或是提供者）是使用提供者RPC的`Web3(Web3.HTTPProvider(provider_rpc))`方式所创建的。您可以通过改变提供者RPC，选择要将交易发送到您指定的网络。
some of this is in English.. and it also looks like there might be an extra `web3` in there

2022-02-28 19:19 UTC, eshaben commented on builders/interact/eth-libraries/deploy-contract.md
> +其次，用来合约交互的文件是 _reset.*_ ，该文件的功能是将合约中存储的数字重置归零。您可以创建一个名为 `increment.js` 或 `increment.py` 的文件，具体取决于您使用的语言。
I think this should be `reset.js`and `reset.py`

2022-03-01 02:05 UTC, hyd628 commented
Thanks. I pushed the fixes.

2022-03-01 15:55 UTC, merged