Minor changes and Sidecar page update
PureStake/moonbeam-docs-cn pull request #63
Opened 2022-03-03 16:55 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/253
https://github.com/PureStake/moonbeam-docs/pull/259

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-03-03 17:43 UTC, eshaben requested changes

2022-03-03 17:43 UTC, eshaben commented on builders/tools/sidecar.md
> +=== "Moonbeam Dev Node"
this should remain as it was, it seems like we have it as `=== "Moonbeam开发节点"` everywhere else

2022-03-03 17:43 UTC, eshaben commented on node-operators/networks/tracing-node.md
> +  - **`--wasm-runtime-overrides=/moonbeam/<network>-substitutes-tracing`** — **必备** 用于追踪指定存储本地WASM runtime路径的标识。接受网络作为参数`moonbeam`、`moonriver`或`moonbase``moonbase`（用于开发节点和 Moonbase Alpha）
looks like there is an extra `moonbase` here but not sure

2022-03-04 00:50 UTC, hyd628 commented
Thanks @eshaben . Fixed issues.

2022-03-04 19:55 UTC, eshaben approved these changes
Thanks Henry! LGTM ✨

2022-03-04 21:04 UTC, merged