Seo updates
PureStake/moonbeam-docs-cn pull request #83
Opened 2022-05-03 09:56 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/288
https://github.com/PureStake/moonbeam-docs/pull/293
https://github.com/PureStake/moonbeam-docs/pull/297

### Checklist

- [ ] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [ ] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [ ] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-05-03 09:57 UTC, hyd628 commented
@eshaben I skipped the files that are touched by other pending PR's

2022-05-04 03:31 UTC, eshaben requested changes
This was a tough one to review, so I'm sure it wasn't easy to create 😅 

All of the index.md files from this PR still need to be translated: https://github.com/PureStake/moonbeam-docs/pull/293/files

Minor changes in this PR https://github.com/PureStake/moonbeam-docs/pull/297/files# are missing for the following pages:
- tokens/manage/identity.md
- builders/integrations/analytics/dapplooker.md (Not sure if what already exists is enough, but please double check it)

A lot of comments were about this URL /builders/get-started/moonbase/#get-tokens/ not being updated to /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on learn/platform/tokens.md
>  # 概览
line 33 should use this updated URL /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on node-operators/networks/collators/faq.md
>  ---
line 174 should use this updated URL /tokens/manage/identity/

2022-05-04 03:31 UTC, eshaben commented on node-operators/networks/run-a-node/overview.md
line 93 should use this latest URL /builders/build/eth-api/debug-trace

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/ledger.md
> +title: 使用Ledger硬件钱包与Moonbeam交互
shouldn't include Moonbeam... should just be Connect & Use Ledger

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/ledger.md
line 120 should use this updated URL /builders/get-started/networks/moonbase/#get-tokens

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/mathwallet.md
line 14 should use updated URL /builders/build/eth-api/dev-env/remix/

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/mathwallet.md
and line 104

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/nifty.md
> +Nifty钱包为Web3工具的提供者，如[Remix](/builders/build/eth-api/dev-env/remix/)。通过将Nifty钱包连接至Moonbeam网络之一，您可以如同在MetaMask上部署合约般部署合约，并且通过Nifty签署交易。本教程会使用Moonbase Alpha测试网，但也适用于Moonbeam和Moonriver。
line 78 should use the latest URL /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on tokens/connect/trezor.md
line 87 should use this updated URL /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on tokens/manage/multisig-safe.md
line 29 should use this updated URL /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on tokens/manage/proxy-accounts.md
line 24  should use this updated URL /builders/get-started/networks/moonbase/#get-tokens/

2022-05-04 03:31 UTC, eshaben commented on tokens/staking/stake.md
line 293 should use this updated URL /learn/features/staking/#reward-distribution

2022-05-05 17:45 UTC, hyd628 commented
@eshaben builders/integrations/analytics/dapplooker.md is being translated by CryptoDiscover on Trello (i havent made a jira ticket for it).

2022-05-05 19:28 UTC, eshaben requested changes
just one last thing!

2022-05-05 19:28 UTC, eshaben commented on builders/build/substrate-api/index.md
> +description:
this one's missing... English version is:

```
Learn how to interact with the Substrate API when developing on Moonbeam, including how to use the Polkadot.js API for querying Moonbeam data.
```

2022-05-05 19:28 UTC, eshaben commented on builders/integrations/oracles/razor-network.md
> +![Razor check price](/images/builders/integrations/oracles/razor/razor-demo-2.png)
```suggestion
![Razor check price](/images/builders/integrations/oracles/razor/razor-demo-2.png)

--8<-- 'text/disclaimers/third-party-content.md'
```

2022-05-05 19:28 UTC, eshaben commented on learn/platform/tokens.md
> +description: 每个Moonbeam网络都需要一个实用代币才能运行 - Polkadot上Moonbeam的Glimmer(GLMR)和Kusama上Moonriver的Moonriver(MVR)。
```suggestion
description: 每个Moonbeam网络都需要一个实用代币才能运行 - Polkadot上Moonbeam的Glimmer(GLMR)和Kusama上Moonriver的Moonriver(MOVR)。
```

2022-05-06 00:13 UTC, hyd628 commented
OK fixed it. Thanks @eshaben .

2022-05-06 04:22 UTC, eshaben approved these changes
Huge effort! Nice job!! 🙌 

🚀 🚢  ✨

2022-05-06 04:22 UTC, merged