Adds orbiter page
PureStake/moonbeam-docs-cn pull request #96
Opened 2022-05-23 13:57 UTC by hyd628

### Description/Original PRs

https://github.com/PureStake/moonbeam-docs/pull/310

### Checklist

- [x] If this requires removing old images from the `moonbeam-docs` repo, I have created a corresponding PR
- [x] If this requires adding/updating/deleting redirects, I have created a corresponding PR in the `moonbeam-mkdocs` repo
- [x] If this requires removing old variables from the `moonbeam-docs` repo, I have created a corresponding PR

### Corresponding PRs

Please link to any additional corresponding PRs here.

2022-05-24 14:53 UTC, eshaben requested changes
just a small change needed! other than that it looks good!

2022-05-24 14:53 UTC, eshaben commented on node-operators/networks/collators/orbiter.md
> +    {{ networks.moonbase.orbiter.max_collators }} Program Collators
```suggestion
    ```
    {{ networks.moonbase.orbiter.max_collators }} Program Collators
    ```

```

2022-05-24 14:53 UTC, eshaben commented on node-operators/networks/collators/orbiter.md
> +- 由于计划本身要求，每个Orbiter必须通过KYC检查且不能为特定国家的居民
just need to swap KYC for identity verification

2022-05-24 14:53 UTC, eshaben commented on node-operators/networks/collators/orbiter.md
> +要加入Orbiter计划，您将需要填写申请表单并提交联系方式、社群媒体账号以及收集人和节点详情。在表格最后，您将需要根据操作流程完成KYC。
just need to swap KYC for identity verification

2022-05-24 14:53 UTC, eshaben commented on node-operators/networks/collators/orbiter.md
> +当您通过了KYC并成功通过此次计划的申请，您将会收到通知并开始进行加入流程，以下为加入流程的步骤：
just need to swap KYC for identity verification

2022-05-25 08:25 UTC, hyd628 commented
Thanks @eshaben , incorporated the feedback.

2022-05-26 03:26 UTC, eshaben approved these changes
LGTM ✨

2022-05-26 03:32 UTC, merged